services:
  sono-website:
    image: ghcr.io/appsono/sono-website:latest
    pull_policy: always
    container_name: sono-website
    restart: unless-stopped
    ports:
      - "${PORT:?set PORT in .env}:80"
